# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- dev

pool:
  vmImage: ubuntu-latest
  
variables:
  - group: lively-expert-dev

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '>=18.17.0'
  displayName: 'Install Node.js'

- script: |
       npm install --legacy-peer-deps

  displayName: 'npm install'
      
- script: |
    npm run build
  displayName: 'npm run build'

- task: CopyFiles@2
  displayName: 'Copy files to prod directory'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: |
       .next/**
       package.json
       next.config.js
    TargetFolder: '$(Build.ArtifactStagingDirectory)/app'
- script: |
    echo  "NEXTAUTH_SECRET=$(NEXTAUTH_SECRET)" > $(Build.ArtifactStagingDirectory)/app/.env
    echo  "NEXT_PUBLIC_GOOGLE_MAP_API_KEY=$(NEXT_PUBLIC_GOOGLE_MAP_API_KEY)" >> $(Build.ArtifactStagingDirectory)/app/.env
    echo  "NEXT_PUBLIC_AUTH_BACKEND_URL=$(NEXT_PUBLIC_AUTH_BACKEND_URL)" >> $(Build.ArtifactStagingDirectory)/app/.env
    echo  "NEXT_PUBLIC_WELLBEING_BACKEND_URL=$(NEXT_PUBLIC_WELLBEING_BACKEND_URL)" >> $(Build.ArtifactStagingDirectory)/app/.env
    echo  "NEXT_PUBLIC_SERVICE_BACKEND_URL=${NEXT_PUBLIC_SERVICE_BACKEND_URL}" >>$(Build.ArtifactStagingDirectory)/app/.env
    echo  "NEXTAUTH_URL=${NEXTAUTH_URL}" >>$(Build.ArtifactStagingDirectory)/app/.env
    echo  "NEXT_APP_BACKEND_URL=${NEXT_APP_BACKEND_URL}" >>$(Build.ArtifactStagingDirectory)/app/.env
    #echo "VITE_REACT_APP_IMAGE_TOKEN=${VITE_REACT_APP_IMAGE_TOKEN}" >>$(Build.ArtifactStagingDirectory)/app/.env

- task: ArchiveFiles@2
  displayName: 'Create zip archive'
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/app'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/app.zip'
    ArtifactName: 'livelyexpertdev'